# Module: axis_dwidth_converter_1
# File:   build/example.inst/axis_dwidth_converter_1.tcl
# Date:   12:04 04/06/2021
# Type:   tcl
# DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER

create_project -part xczu3eg-sbva484-1-e -in_memory
read_ip /home/alex/GitHub/zycap2/zycap/test/demo/rtl/gaussian/axis_dwidth_converter_1.xci
generate_target instantiation_template [get_files /home/alex/GitHub/zycap2/zycap/test/demo/rtl/gaussian/axis_dwidth_converter_1.xci]
close_project
exit