site_name: ZyCAP2 Docs
site_url: https://example.com/foo/

nav:
  - Intro: 'index.md'
  - Installation: 'installation.md'
  - CLI: 'cli.md'
  - Getting Started: 'getting-started.md'
  - Guides:
    - API: '!include docs/api/mkdocs.yml'
    - Hardware: '!include docs/hdl/mkdocs.yml'
    - Linux: '!include docs/linux/mkdocs.yml'
    - Runtime: '!include docs/runtime/mkdocs.yml'
  - Notes: 'notes.md'
  - Publications: 'publications.md'
  - Glossary: 'glossary.md'
  - Bibliography: 'references.md'
  - Cite: 'cite.md'

plugins:
  - monorepo

markdown_extensions:
  - mkdocs-click
  - pymdownx.superfences
theme: 
  name: material
  logo: 'images/gear.svg'
  icon:
    logo: material/bookmark
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-sunny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  search:
    language: 'en'

repo_name: 'warc/zycap'
repo_url: 'https://github.com/warc/zycap2'