webtalk_init -webtalk_dir /home/alex/GitHub/zycap2/example/linux/zycap/sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-01-07 22:12:39" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174217199_1777515649_210675447_365" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8oahjke23dt2v2nfukp7na7vf6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "900.024 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.695 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1578418516000" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key projSize -value "70.7734375" -context "sdk\\\\application/1578418516000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key DebugCount -value "9" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1578435159742"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1578435159742"
webtalk_transmit -clientid 1005854416 -regid "174217199_1777515649_210675447_365" -xml /home/alex/GitHub/zycap2/example/linux/zycap/sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/alex/GitHub/zycap2/example/linux/zycap/sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/alex/GitHub/zycap2/example/linux/zycap/sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
