/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* generator = "nMigen" *)
(* top =  1  *)
(* \nmigen.hierarchy  = "blink" *)
module blink(led, rst, clk);
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" *)
  wire \$1 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:18" *)
  wire [32:0] \$3 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:18" *)
  wire [32:0] \$4 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" *)
  wire \$6 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:16" *)
  wire \$8 ;
  (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* init = 32'd0 *)
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:12" *)
  reg [31:0] count = 32'd0;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:12" *)
  reg [31:0] \count$next ;
  (* init = 1'h0 *)
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:7" *)
  output led;
  reg led = 1'h0;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:7" *)
  reg \led$next ;
  (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  assign \$1  = count == (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" *) 29'h1dcd6500;
  assign \$4  = count + (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:18" *) 1'h1;
  assign \$6  = count == (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" *) 29'h1dcd6500;
  assign \$8  = ~ (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:16" *) led;
  always @(posedge clk)
      led <= \led$next ;
  always @(posedge clk)
      count <= \count$next ;
  always @* begin
    \count$next  = count;
    (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" *)
    casez (\$1 )
      /* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" */
      1'h1:
          \count$next  = 32'd0;
      /* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:17" */
      default:
          \count$next  = \$3 [31:0];
    endcase
    (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \count$next  = 32'd0;
    endcase
  end
  always @* begin
    \led$next  = led;
    (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" *)
    casez (\$6 )
      /* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/test.py:14" */
      1'h1:
          \led$next  = \$8 ;
    endcase
    (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \led$next  = 1'h0;
    endcase
  end
  assign \$3  = \$4 ;
endmodule

