/*
* Module: test
* File:   rtl/test.v
* Date:   17:37 30/12/2020
* Type:   verilog
* DO NOT MODIFY THIS FILE; AUTOMATICALLY GENERATED BY INTERFACER
*/

module test (
    input aclk, 
    input [15 : 0] s_axis_config_tdata, 
    input s_axis_config_tvalid, 
    output s_axis_config_tready, 
    input [31 : 0] s_axis_data_tdata, 
    input s_axis_data_tvalid, 
    output s_axis_data_tready, 
    input s_axis_data_tlast, 
    output [31 : 0] m_axis_data_tdata, 
    output m_axis_data_tvalid, 
    input m_axis_data_tready, 
    output m_axis_data_tlast, 
    output event_frame_started, 
    output event_tlast_unexpected, 
    output event_tlast_missing, 
    output event_status_channel_halt, 
    output event_data_in_channel_halt, 
    output event_data_out_channel_halt 
);
    
endmodule
