/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* generator = "nMigen" *)
(* top =  1  *)
(* \nmigen.hierarchy  = "top" *)
module top(bus__addr, bus__r_data, bus__w_data, bus__we, clk, rst, pins);
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:20" *)
  input [2:0] bus__addr;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:20" *)
  output bus__r_data;
  reg bus__r_data;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:20" *)
  input bus__w_data;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:20" *)
  input bus__we;
  (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* init = 8'h00 *)
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:26" *)
  output [7:0] pins;
  reg [7:0] pins = 8'h00;
  (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:26" *)
  reg [7:0] \pins$next ;
  (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  always @(posedge clk)
      pins <= \pins$next ;
  always @* begin
    bus__r_data = 1'h0;
    (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:13" *)
    casez (bus__addr)
      3'h0:
          bus__r_data = pins[0];
      3'h1:
          bus__r_data = pins[1];
      3'h2:
          bus__r_data = pins[2];
      3'h3:
          bus__r_data = pins[3];
      3'h4:
          bus__r_data = pins[4];
      3'h5:
          bus__r_data = pins[5];
      3'h6:
          bus__r_data = pins[6];
      3'hz:
          bus__r_data = pins[7];
    endcase
  end
  always @* begin
    \pins$next  = pins;
    (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:14" *)
    casez (bus__we)
      /* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:14" */
      1'h1:
          (* src = "/home/alex/GitHub/zycap2/zycap/boards/em.avnet.com/ultra96v2/part0/1.0/src/gpio.py:15" *)
          casez (bus__addr)
            3'h0:
                \pins$next [0] = bus__w_data;
            3'h1:
                \pins$next [1] = bus__w_data;
            3'h2:
                \pins$next [2] = bus__w_data;
            3'h3:
                \pins$next [3] = bus__w_data;
            3'h4:
                \pins$next [4] = bus__w_data;
            3'h5:
                \pins$next [5] = bus__w_data;
            3'h6:
                \pins$next [6] = bus__w_data;
            3'hz:
                \pins$next [7] = bus__w_data;
          endcase
    endcase
    (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \pins$next  = 8'h00;
    endcase
  end
endmodule

