site_name: ZyCAP2 Docs

nav:
  - Intro: 'index.md'
  - Getting Started: 'getting-started.md'
  - Guides:
    - Hardware: '!include ./hdl/mkdocs.yml'
    - Software: '!include ./sw/mkdocs.yml'
    - Linux: '!include ./linux/mkdocs.yml'
  - References: 'references.md'

plugins:
  - monorepo

theme: 
  name: material
  palette:
    primary: 'black'
    accent: 'indigo'
  logo: 'images/gear.svg'

extra:
  search:
    language: 'en'

repo_name: 'warc/zycap'
repo_url: 'https://github.com/warc/zycap2'