/* Generated by ZyCAP Toolflow */
/* DO NOT EDIT THIS FILE */
/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* generator = "nMigen" *)
(* top =  1  *)
(* \nmigen.hierarchy  = "icape" *)
module icape(done, rw, err, m_axis_tdata, m_axis_tready, m_axis_tvalid, s_axis_tdata, s_axis_tready, s_axis_tvalid, s_axis_tlast, rst, clk);
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:157" *)
  wire \$1 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" *)
  wire \$3 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:126" *)
  wire \$5 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" *)
  wire \$7 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:126" *)
  wire \$9 ;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:104" *)
  wire avail;
  (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/ir.py:526" *)
  input clk;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:107" *)
  reg [31:0] data_in;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:108" *)
  wire [31:0] data_out;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:72" *)
  output done;
  (* init = 1'h0 *)
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:74" *)
  output err;
  reg err = 1'h0;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:74" *)
  reg \err$next ;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:105" *)
  wire error;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:77" *)
  output [31:0] m_axis_tdata;
  reg [31:0] m_axis_tdata;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:78" *)
  input m_axis_tready;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:79" *)
  output m_axis_tvalid;
  reg m_axis_tvalid;
  (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/ir.py:526" *)
  input rst;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:73" *)
  input rw;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:83" *)
  input [31:0] s_axis_tdata;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:86" *)
  input s_axis_tlast;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:84" *)
  output s_axis_tready;
  reg s_axis_tready;
  (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:85" *)
  input s_axis_tvalid;
  assign \$9  = rw == (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:126" *) 1'h0;
  assign \$1  = ~ (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:157" *) s_axis_tvalid;
  assign \$3  = rw == (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" *) 1'h1;
  assign \$5  = rw == (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:126" *) 1'h0;
  assign \$7  = rw == (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" *) 1'h1;
  always @(posedge clk)
      err <= \err$next ;
  ICAPE3 #(
    .DEVICE_ID(32'd3735928559),
    .ICAP_AUTO_SWITCH("DISABLED"),
    .SIM_CFG_FILE_NAME("NONE")
  ) icap (
    .AVAIL(avail),
    .CLK(clk),
    .CSIB(\$1 ),
    .I(data_in),
    .O(data_out),
    .PRDONE(done),
    .PRERROR(error),
    .RDWRB(rw)
  );
  always @* begin
    \err$next  = err;
    \err$next  = error;
    (* src = "/home/alex/.pyenv/versions/zycap/lib/python3.9/site-packages/nmigen/hdl/xfrm.py:530" *)
    casez (rst)
      1'h1:
          \err$next  = 1'h0;
    endcase
  end
  always @* begin
    data_in = 32'd0;
    data_in[7:0] = { s_axis_tdata[24], s_axis_tdata[25], s_axis_tdata[26], s_axis_tdata[27], s_axis_tdata[28], s_axis_tdata[29], s_axis_tdata[30], s_axis_tdata[31] };
    data_in[15:8] = { s_axis_tdata[16], s_axis_tdata[17], s_axis_tdata[18], s_axis_tdata[19], s_axis_tdata[20], s_axis_tdata[21], s_axis_tdata[22], s_axis_tdata[23] };
    data_in[23:16] = { s_axis_tdata[8], s_axis_tdata[9], s_axis_tdata[10], s_axis_tdata[11], s_axis_tdata[12], s_axis_tdata[13], s_axis_tdata[14], s_axis_tdata[15] };
    data_in[31:24] = { s_axis_tdata[0], s_axis_tdata[1], s_axis_tdata[2], s_axis_tdata[3], s_axis_tdata[4], s_axis_tdata[5], s_axis_tdata[6], s_axis_tdata[7] };
  end
  always @* begin
    m_axis_tdata = 32'd0;
    m_axis_tdata[7:0] = { data_out[24], data_out[25], data_out[26], data_out[27], data_out[28], data_out[29], data_out[30], data_out[31] };
    m_axis_tdata[15:8] = { data_out[16], data_out[17], data_out[18], data_out[19], data_out[20], data_out[21], data_out[22], data_out[23] };
    m_axis_tdata[23:16] = { data_out[8], data_out[9], data_out[10], data_out[11], data_out[12], data_out[13], data_out[14], data_out[15] };
    m_axis_tdata[31:24] = { data_out[0], data_out[1], data_out[2], data_out[3], data_out[4], data_out[5], data_out[6], data_out[7] };
  end
  always @* begin
    s_axis_tready = 1'h0;
    (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" *)
    casez ({ \$5 , \$3  })
      /* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" */
      2'bz1:
          s_axis_tready = avail;
    endcase
  end
  always @* begin
    m_axis_tvalid = 1'h0;
    (* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" *)
    casez ({ \$9 , \$7  })
      /* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:124" */
      2'bz1:
          /* empty */;
      /* src = "/home/alex/GitHub/zycap2/zycap/ip/icap/2019.2/icape.py:126" */
      2'b1z:
          m_axis_tvalid = avail;
    endcase
  end
endmodule
