site_name: ZyCAP2 Docs
site_url: https://example.com/foo/

nav:
  - Intro: 'index.md'
  - Getting Started: 'getting-started.md'
  - Guides:
    - Hardware: '!include ./hdl/mkdocs.yml'
    - Linux: '!include ./linux/mkdocs.yml'
    - Runtime: '!include ./api/mkdocs.yml'
  - Notes: 'notes.md'
  - Publications: 'publications.md'
  - References: 'references.md'
  - Citation: 'cite.md'

plugins:
  - monorepo

theme: 
  name: material
  palette:
    primary: 'black'
    accent: 'indigo'
  logo: 'images/gear.svg'

extra:
  search:
    language: 'en'

repo_name: 'warc/zycap'
repo_url: 'https://github.com/warc/zycap2'