name: Issue Generator
on:
  push:
    branches: [ develop-python ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop-python
    - name: Run tdg-github-action
      uses: ribtoks/tdg-github-action@master
      with:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        SHA: ${{ github.sha }}
        REF: ${{ github.ref }}