name: versionist

on:
  push:
    branches:
      - "master"

jobs:
  versionist:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      # requires with 'repo' access.
      # using GITHUB_TOKEN will NOT trigger other workflows
      - id: versionist
        uses: tmigone/versionist@v0.4.6
        with:
          github_email: "alexbucknall+warclab@gmail.com"
          github_username: "warclab-version"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master